# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            CSC3220
tagline:          'Syllabus'
description:      'Applications Programming Spring 2020 Syllabus @ Seattle Pacific University.'
url:              'https://twpspu.github.io'
baseurl:          '/csc3220w20'

coursecode:       'CSC 3220'
coursetitle:      'Applications Programming'
term:             'Spring 2020'
instructor:       'Dr. Taiwoo Park'
office:           'OMH 208'
email:            'twp@spu.edu'
phone:            '206-286-7258'

author:
  name:           'Taiwoo Park'
  url:            https://twpark.tw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
gems:
  - jekyll-pdf
