# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            CSC3220
tagline:          'Syllabus'
description:      'Applications Programming Winter 2020 Syllabus @ Seattle Pacific University.'
url:              "https://twpspu.github.io"
baseurl:          "/csc3220w20"

author:
  name:           'Taiwoo Park'
  url:            https://twpark.tw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
gems:
  - jekyll-pdf
